services:
  firestore-emulator:
    container_name: firestore-emulator
    image: google/cloud-sdk:514.0.0-emulators
    platform: linux/amd64
    expose:
      - 5173
    ports:
      - "5173:5173"
    command: [ "gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:5173" ]

  k33-backend:
    container_name: k33-backend
    build: apps/k33-backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - FIRESTORE_EMULATOR_HOST=firestore-emulator:5173
      - JAVA_OPTS=-Dlogback.configurationFile=logback.xml
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_WEBHOOK_ENDPOINT_SECRET=${STRIPE_WEBHOOK_ENDPOINT_SECRET}
      - STRIPE_PRODUCT_ID_RESEARCH_TWIC=${STRIPE_PRODUCT_ID_RESEARCH_TWIC}
      - STRIPE_PRODUCT_ID_RESEARCH_NN=${STRIPE_PRODUCT_ID_RESEARCH_NN}
      - STRIPE_PRODUCT_ID_RESEARCH_AOC=${STRIPE_PRODUCT_ID_RESEARCH_AOC}
      - STRIPE_PRODUCT_ID_RESEARCH_PRO=${STRIPE_PRODUCT_ID_RESEARCH_PRO}
      - STRIPE_COUPON_CORPORATE_PLAN=${STRIPE_COUPON_CORPORATE_PLAN}
      - METRICS_ENABLED=false
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_ENABLED=false
      - CONTENTFUL_LEGAL_SPACE_ID=${CONTENTFUL_LEGAL_SPACE_ID}
      - CONTENTFUL_LEGAL_SPACE_TOKEN=${CONTENTFUL_LEGAL_SPACE_TOKEN}
      - CONTENTFUL_RESEARCH_SPACE_ID=${CONTENTFUL_RESEARCH_SPACE_ID}
      - CONTENTFUL_RESEARCH_SPACE_TOKEN=${CONTENTFUL_RESEARCH_SPACE_TOKEN}
      - CONTENTFUL_RESEARCH_SPACE_CMA_TOKEN=${CONTENTFUL_RESEARCH_SPACE_CMA_TOKEN}
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_API_KEY=${ALGOLIA_API_KEY}
      - SLACK_ALERTS_CHANNEL_ID=${SLACK_ALERTS_CHANNEL_ID}
      - SLACK_GENERAL_CHANNEL_ID=${SLACK_GENERAL_CHANNEL_ID}
      - SLACK_INVEST_CHANNEL_ID=${SLACK_INVEST_CHANNEL_ID}
      - SLACK_PRODUCT_CHANNEL_ID=${SLACK_PRODUCT_CHANNEL_ID}
      - SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID=${SLACK_PROFESSIONAL_INVESTORS_CHANNEL_ID}
      - SLACK_RESEARCH_CHANNEL_ID=${SLACK_RESEARCH_CHANNEL_ID}
      - SLACK_RESEARCH_EVENTS_CHANNEL_ID=${SLACK_RESEARCH_EVENTS_CHANNEL_ID}
      - SLACK_VAULT_ADMIN_CHANNEL_ID=${SLACK_VAULT_ADMIN_CHANNEL_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_TWIC=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_TWIC}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_NN=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_NN}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_AOC=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_AOC}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_PRO_TRIAL=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_PRO_TRIAL}
      - SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_PRO=${SENDGRID_TEMPLATE_ID_WELCOME_TO_K33_RESEARCH_PRO}
      - SENDGRID_TEMPLATE_ID_CANCEL_DURING_TRIAL_K33_RESEARCH_PRO=${SENDGRID_TEMPLATE_ID_CANCEL_DURING_TRIAL_K33_RESEARCH_PRO}
      - SENDGRID_TEMPLATE_ID_NEW_USER_OFFER_K33_RESEARCH=${SENDGRID_TEMPLATE_ID_NEW_USER_OFFER_K33_RESEARCH}
      - SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_TWIC=${SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_TWIC}
      - SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_NN=${SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_NN}
      - SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_AOC=${SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_AOC}
      - SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_PRO=${SENDGRID_CONTACT_LIST_ID_K33_RESEARCH_PRO}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_TWIC=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_TWIC}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_NN=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_NN}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_AOC=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_AOC}
      - SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_PRO=${SENDGRID_UNSUBSCRIBE_GROUP_ID_K33_RESEARCH_PRO}
      - GOOGLE_ANALYTICS_API_SECRET=${GOOGLE_ANALYTICS_API_SECRET}
      - GOOGLE_ANALYTICS_FIREBASE_APP_ID=${GOOGLE_ANALYTICS_FIREBASE_APP_ID}
      - GOOGLE_ANALYTICS_MEASUREMENT_ID=${GOOGLE_ANALYTICS_MEASUREMENT_ID}
      - INVEST_DENIED_COUNTRY_CODE_LIST=${INVEST_DENIED_COUNTRY_CODE_LIST}
      - INVEST_EMAIL_FROM=${INVEST_EMAIL_FROM}
      - INVEST_EMAIL_TO_LIST=${INVEST_EMAIL_TO_LIST}
      - INVEST_EMAIL_CC_LIST=${INVEST_EMAIL_CC_LIST}
      - INVEST_EMAIL_BCC_LIST=${INVEST_EMAIL_BCC_LIST}
      - FIREBLOCKS_API_KEY=${FIREBLOCKS_API_KEY}
      - FIREBLOCKS_SECRET_KEY=${FIREBLOCKS_SECRET_KEY}
      - COIN_GECKO_API_KEY=${COIN_GECKO_API_KEY}
      - VAULT_STRIPE_API_KEY=${VAULT_STRIPE_API_KEY}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - firestore-emulator

  acceptance-tests:
    container_name: acceptance-tests
    build: apps/acceptance-tests
    environment:
      - BACKEND_HOST=k33-backend
      - GOOGLE_APPLICATION_CREDENTIALS=/config/gcp-service-account.json
      - CONTENTFUL_LEGAL_SPACE_ID=${CONTENTFUL_LEGAL_SPACE_ID}
      - CONTENTFUL_TEST_PAGE_ID=${CONTENTFUL_TEST_PAGE_ID}
      - CONTENTFUL_TEST_REPORT_ID=${CONTENTFUL_TEST_REPORT_ID}
      - STRIPE_PRODUCT_ID_RESEARCH_PRO=${STRIPE_PRODUCT_ID_RESEARCH_PRO}
      - STRIPE_PRICE_ID_RESEARCH_PRO=${STRIPE_PRICE_ID_RESEARCH_PRO}
    volumes:
      - "./infra/gcp/secrets/gcp-service-account.json:/config/gcp-service-account.json:ro"
    depends_on:
      - k33-backend