### Get all payment subscription products

GET https://api.k33.com/payment/subscribed-products
Authorization: Bearer {{firebase_id_token}}

### Get all payment subscription product

GET https://api.k33.com/payment/subscribed-products/{{stripe_product_id_research_pro}}
Authorization: Bearer {{firebase_id_token}}

###

POST https://api.k33.com/payment/checkout-sessions
Authorization: Bearer {{firebase_id_token}}
Content-Type: application/json

{
  "price_id": "",
  "success_url": "",
  "cancel_url": ""
}

###

POST https://api.k33.com/payment/customer-portal-sessions
Authorization: Bearer {{firebase_id_token}}
Content-Type: application/json

{
  "return_url": ""
}