### Get vault account assets

GET https://api.k33.com/apps/vault/assets
Authorization: Bearer {{firebase_id_token}}

### Get vault transactions by admin

GET https://api.k33.com/apps/vault/admin/transactions
    ?vaultAccountId={{vault_account_id}}
    &afterDate=2023-01-01
    &beforeDate=2023-12-31
X-API-KEY: {{admin_api_key}}