### fetch articleWeb ids

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleWebCollection(limit: 11000) {
        items {
            sys {
                id
                publishedAt
            }
        }
    }
}

### fetch articleWeb list

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleWebCollection(limit: 5500) {
        items {
            article {
                sys {
                    id
                }
            }
            sys {
                id
            }
        }
    }
}

### fetch articleWeb by id

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query($articleWebId: String!) {
    articleWebCollection(where: { sys: { id: $articleWebId } }, limit: 1) {
        items {
            article {
                sys {
                    id
                }
            }
            sys {
                id
            }
        }
    }
}

### fetch articleWeb list using section

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleWebCollection(
        where: {
            sections: { name: "" }
        },
        order: [publishedDate_DESC],
        limit: 11000
    ) {
        items {
            title
            articleSlug
            publishedDate
        }
    }
}

