### fetch article ids

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleCollection(limit: 11000) {
        items {
            sys {
                id
                publishedAt
            }
        }
    }
}

### fetch all articles

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleCollection(limit: 785) {
        items {
            title
            subtitle
            body {
                json
            }
            image {
                title
                url
            }
            authorsCollection {
                items {
                    name
                }
            }
            summary {
                json
            }
            keyPoints
            tagsCollection {
                items {
                    title
                }
            }
            publishedDate
            sys {
                id
                publishedAt
            }
            articleSlug
            sectionsCollection {
                items {
                    name
                }
            }
        }
    }
}

### fetch article by id

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleCollection(where: { sys: { id: "" } }, limit: 1) {
        items {
            title
            subtitle
            body {
                json
            }
            image {
                title
                url
            }
            authorsCollection {
                items {
                    title
                    description
                }
            }
            summary {
                json
            }
            keyPoints
            tagsCollection {
                items {
                    title
                }
            }
            publishedDate
            sys {
                id
                publishedAt
            }
            articleSlug
            sectionsCollection {
                items {
                    name
                }
            }
        }
    }
}

### fetch images

GRAPHQL https://graphql.contentful.com/content/v1/spaces/{{space_id}}
Content-Type: application/graphql
Authorization: Bearer {{token}}

query {
    articleCollection(limit: 2750) {
        items {
            image {
                height
                width
                contentType
                fileName
            }
            horizontalThumbnail {
                height
                width
                contentType
                fileName
            }
            verticalThumbnail {
                height
                width
                contentType
                fileName
            }
            coverPicture {
                height
                width
                contentType
                fileName
            }
        }
    }
}