@startuml

class section

class article

author <... article : always has many <
tag <... article : always has 1 to 5 <

class articleWeb
article <|-- articleWeb : always has 1 <

section <... articleWeb : always has 1 to 2 <

subscriptionWeb <... articleWeb : always has 1

class author

class seoMetadata

class subscription

class subscriptionProduct

subscription <.. subscriptionProduct : always prices many <

class subscriptionWeb

subscription <|-- subscriptionWeb
seoMetadata <... subscriptionWeb : always has 1 <

class tag

class token

class indexToken
token <.. indexToken : always has 1 <

class index
indexToken <.. index : always has many <

class news

@enduml