@startuml

class section

class article

author <... article : always has many <
tag <... article : always has 1 to 5 <

section <... article : always has 1 to 2 <
seoMetadata <... article : has 1 <

class author

class seoMetadata

class tag

class token

class indexToken
token <.. indexToken : always has 1 <

class index
indexToken <.. index : always has many <

class news

@enduml