name: Deploy API gateway to GCP
on:
  workflow_dispatch:
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_ID: api.k33.com
  ESP_FULL_VERSION: 2.48.0
jobs:
  deploy-endpoints:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3
      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GCP_PROJECT_ID: op://k33-platform-env/prod/gcp/GCP_PROJECT_ID
          GCP_API_HOST: op://k33-platform-env/prod/gcp/GCP_API_HOST
          GCP_BACKEND_HOST: op://k33-platform-env/prod/gcp/GCP_BACKEND_HOST
          CORS_REGEX: op://k33-platform-env/prod/gcp/CORS_REGEX
          GCP_WORKLOAD_IDENTITY_PROVIDER: op://k33-platform-env/github/gcp/GCP_WORKLOAD_IDENTITY_PROVIDER
          GCP_SERVICE_ACCOUNT: op://k33-platform-env/github/gcp/GCP_SERVICE_ACCOUNT
      - name: Google auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Deploy GCP Cloud Endpoints
        run: |
          TMP_DIR=$(mktemp -d)
          echo "$TMP_DIR"
          TMP_FILE="$TMP_DIR/k33-backend-api.yaml"
          trap 'rm -rf "$TMP_DIR"' EXIT
          sed 's~${GCP_PROJECT_ID}~'"${GCP_PROJECT_ID}"'~g; s~${GCP_API_HOST}~'"${GCP_API_HOST}"'~g; s~${GCP_BACKEND_HOST}~'"${GCP_BACKEND_HOST}"'~g' libs/clients/k33-backend-client/src/main/openapi/k33-backend-api.yaml > "$TMP_FILE"
          gcloud endpoints services deploy "$TMP_FILE"
      - name: Fetch Endpoints Service Config ID
        run: echo "SERVICE_CONFIG_ID=$(gcloud endpoints configs list --service api.k33.com --format=object --flatten=id --sort-by=~id --limit=1)" >> $GITHUB_ENV
      - name: Build & push custom ESP v2 docker image for GCP Cloud Run
        working-directory: apps/esp-v2
        run: |-
          ./gcloud_build_image.sh \
            -s $SERVICE_ID \
            -c $SERVICE_CONFIG_ID \
            -p $GCP_PROJECT_ID \
            -v $ESP_FULL_VERSION \
            -g europe-docker.pkg.dev/$GCP_PROJECT_ID/backend \
            -r $CORS_REGEX
      - name: Deploy ESP v2
        run: |-
          gcloud run deploy k33-backend-gateway \
            --region europe-west1 \
            --image europe-docker.pkg.dev/$GCP_PROJECT_ID/backend/endpoints-runtime-serverless:$ESP_FULL_VERSION-$SERVICE_ID-$SERVICE_CONFIG_ID \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=1 \
            --max-instances=1 \
            --concurrency=1000 \
            --service-account k33-backend-gateway \
            --allow-unauthenticated \
            --port=8080 \
            --platform=managed
